<?php
/**
 * Magento Scheduler  by LeanSwift
 *
 * NOTICE OF LICENSE
 *  This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, Version 3 of the License. You can view
 *   the license here http://opensource.org/licenses/GPL-3.0

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 * @category    LeanSwift
 * @package     LeanSwift_Scheduler
 * @copyright   Copyright (c) 2017 LeanSwift (http://www.leanswift.com)
 * @license     http://opensource.org/licenses/GPL-3.0 GNU General Public License, version 3 (GPL-3.0)
 *
 */
?>
<?php if ($block->isAllowed()) : /* only if allowed */ ?>
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="">
            <div class="page-actions-buttons">                
                <button id="schedule" title="<?php echo __("Run tasks & Generate Schedule"); ?>" type="button" class="action- scalable primary" onclick="location.href = '<?php echo $block->getGenerateScheduleUrl(); ?>';" data-ui-id="schedule-button">
                    <span><?php echo __("Generate Schedule"); ?></span>
                </button>
            </div>
        </div>
    </div>
<?php endif;